package main

import (
	"context"


	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	pb "github.com/travix/gotf-example/pb"
	providerpb "github.com/travix/gotf-example/provider/providerpb"
)

// This file was generated by protoc-gen-gotf as a scaffold, it can be modified.
// If you want to regenerate the scaffold delete or rename this file and run protoc with protoc-gen-gotf again.

var _ providerpb.GroupResourceExec = &GroupResourceExec{}

type GroupResourceExec struct {
	groupClient pb.GroupServiceClient
	userClient  pb.UserServiceClient
}

func (e *GroupResourceExec) Create(ctx context.Context, _ resource.CreateRequest, _ *resource.CreateResponse, data *pb.Group) (*pb.Group, diag.Diagnostics) {
	user, err := e.groupClient.CreateGroup(ctx, data)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("failed to create group", err.Error())
		return nil, diags
	}
	if len(data.Users) > 0 {
		for _, user := range data.Users {
			_, err := e.userClient.CreateUser(ctx, user)
			if err != nil {
				var diags diag.Diagnostics
				diags.AddError("failed to add users from group", err.Error())
				return nil, diags
			}
		}
	}
	return user, nil
}

func (e *GroupResourceExec) Read(ctx context.Context, _ resource.ReadRequest, _ *resource.ReadResponse, data *pb.Group) (*pb.Group, diag.Diagnostics) {
	group, err := e.groupClient.GetGroup(ctx, &pb.GetGroupRequest{Name: data.Name})
	if err != nil {
		st, ok := status.FromError(err)
		if ok && st.Code() == codes.NotFound {
			return data, nil
		}
		var diags diag.Diagnostics
		diags.AddError("failed to get group", err.Error())
		return nil, diags
	}
	return group, nil
}

func (e *GroupResourceExec) Update(ctx context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse, data *pb.Group) (*pb.Group, diag.Diagnostics) {
	group, err := e.groupClient.UpdateGroup(ctx, data)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("failed to update group", err.Error())
		return nil, diags
	}
	return group, nil
}

func (e *GroupResourceExec) Delete(ctx context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse, data *pb.Group) diag.Diagnostics {
	_, err := e.groupClient.DeleteGroup(ctx, data)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("failed to delete group", err.Error())
		return diags
	}
	return nil
}

func (e *GroupResourceExec) SetGroupServiceClient(client pb.GroupServiceClient) {
	e.groupClient = client
}
func (e *GroupResourceExec) SetUserServiceClient(client pb.UserServiceClient) {
	e.userClient = client
}
