package main

import (
	"context"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	pb "github.com/travix/gotf-example/pb"
	providerpb "github.com/travix/gotf-example/provider/providerpb"
)

// This file was generated by protoc-gen-gotf as a scaffold, it can be modified.
// If you want to regenerate the scaffold delete or rename this file and run protoc with protoc-gen-gotf again.

var _ providerpb.UsersDataSourceExec = &UsersDataSourceExec{}

type UsersDataSourceExec struct {
	userClient pb.UserServiceClient
}

func (e *UsersDataSourceExec) Read(ctx context.Context, _ datasource.ReadRequest, _ *datasource.ReadResponse, _ *pb.Users) (*pb.Users, diag.Diagnostics) {
	tflog.Info(ctx, "reading users from grpc")
	users, err := e.userClient.ListUsers(ctx, &pb.Empty{})
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("failed to list users", err.Error())
		return nil, diags
	}
	return users, nil
}

func (e *UsersDataSourceExec) SetUserServiceClient(client pb.UserServiceClient) {
	e.userClient = client
}
