// Code generated by protoc-gen-gotf. DO NOT EDIT.
// versions:
//   protoc-gen-gotf 0.2.0

package pb

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	dschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	pschema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	rschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

// make sure the proto implements ObjectTypable
var _ attr.TypeWithAttributeTypes = &ProviderModel{} // make sure the proto implements ObjectTypable
var _ attr.TypeWithAttributeTypes = &User{}          // make sure the proto implements ObjectTypable
var _ attr.TypeWithAttributeTypes = &Users{}         // make sure the proto implements ObjectTypable
var _ attr.TypeWithAttributeTypes = &Group{}         // make sure the proto implements ObjectTypable
var _ attr.TypeWithAttributeTypes = &Groups{}
var _ = dschema.Schema{} // to avoid unused import error
var _ = pschema.Schema{} // to avoid unused import error
var _ = rschema.Schema{} // to avoid unused import error

func (x *ProviderModel) ProviderSchema() map[string]pschema.Attribute {
	attributes := map[string]pschema.Attribute{
		"endpoint": pschema.StringAttribute{
			Optional:            true,
			Required:            false,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
		"key_id": pschema.StringAttribute{
			Optional:            false,
			Required:            true,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
		"secret_key": pschema.StringAttribute{
			Optional:            false,
			Required:            true,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
	}
	return attributes
}

func (x ProviderModel) AttributeDefaultValues(ctx context.Context) map[string]tftypes.Value {
	attributes := map[string]tftypes.Value{
		"endpoint": tftypes.NewValue(tftypes.String, ""),
	}
	return attributes
}

func (x *ProviderModel) AttributeTypes() map[string]attr.Type {
	attributes := map[string]attr.Type{
		"endpoint":   types.StringType,
		"key_id":     types.StringType,
		"secret_key": types.StringType,
	}
	return attributes
}

func (x *ProviderModel) WithAttributeTypes(typs map[string]attr.Type) attr.TypeWithAttributeTypes {
	return basetypes.ObjectType{AttrTypes: typs}.WithAttributeTypes(typs)
}

func (x *ProviderModel) TerraformType(ctx context.Context) tftypes.Type {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.TerraformType(ctx)
}

func (x *ProviderModel) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromTerraform(ctx, in)
}

func (x *ProviderModel) Equal(candidate attr.Type) bool {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.Equal(candidate)
}

func (x *ProviderModel) ApplyTerraform5AttributePathStep(step tftypes.AttributePathStep) (interface{}, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ApplyTerraform5AttributePathStep(step)
}

func (x *ProviderModel) ValueType(ctx context.Context) attr.Value {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueType(ctx)
}

func (x *ProviderModel) ValueFromObject(ctx context.Context, obj basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromObject(ctx, obj)
}

func (x *User) ResourceSchema() map[string]rschema.Attribute {
	attributes := map[string]rschema.Attribute{
		"username": rschema.StringAttribute{
			Computed:            false,
			Optional:            false,
			Required:            true,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
		"email": rschema.StringAttribute{
			Computed:            false,
			Optional:            true,
			Required:            false,
			Sensitive:           false,
			Description:         "user email address",
			MarkdownDescription: "user email address",
			DeprecationMessage:  "",
		},
	}
	return attributes
}

func (x User) AttributeDefaultValues(ctx context.Context) map[string]tftypes.Value {
	attributes := map[string]tftypes.Value{
		"email": tftypes.NewValue(tftypes.String, ""),
	}
	return attributes
}

func (x *User) AttributeTypes() map[string]attr.Type {
	attributes := map[string]attr.Type{
		"username": types.StringType,
		"email":    types.StringType,
	}
	return attributes
}

func (x *User) WithAttributeTypes(typs map[string]attr.Type) attr.TypeWithAttributeTypes {
	return basetypes.ObjectType{AttrTypes: typs}.WithAttributeTypes(typs)
}

func (x *User) TerraformType(ctx context.Context) tftypes.Type {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.TerraformType(ctx)
}

func (x *User) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromTerraform(ctx, in)
}

func (x *User) Equal(candidate attr.Type) bool {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.Equal(candidate)
}

func (x *User) ApplyTerraform5AttributePathStep(step tftypes.AttributePathStep) (interface{}, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ApplyTerraform5AttributePathStep(step)
}

func (x *User) ValueType(ctx context.Context) attr.Value {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueType(ctx)
}

func (x *User) ValueFromObject(ctx context.Context, obj basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromObject(ctx, obj)
}

func (x *Users) DatasourceSchema() map[string]dschema.Attribute {
	attributes := map[string]dschema.Attribute{
		"users": dschema.ListAttribute{
			ElementType:         types.ObjectType{AttrTypes: (&User{}).AttributeTypes()},
			Computed:            true,
			Optional:            false,
			Required:            false,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
	}
	return attributes
}

func (x Users) AttributeDefaultValues(ctx context.Context) map[string]tftypes.Value {
	attributes := map[string]tftypes.Value{}
	return attributes
}

func (x *Users) AttributeTypes() map[string]attr.Type {
	attributes := map[string]attr.Type{
		"users": types.ListType{
			ElemType: types.ObjectType{AttrTypes: (&User{}).AttributeTypes()},
		},
	}
	return attributes
}

func (x *Users) WithAttributeTypes(typs map[string]attr.Type) attr.TypeWithAttributeTypes {
	return basetypes.ObjectType{AttrTypes: typs}.WithAttributeTypes(typs)
}

func (x *Users) TerraformType(ctx context.Context) tftypes.Type {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.TerraformType(ctx)
}

func (x *Users) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromTerraform(ctx, in)
}

func (x *Users) Equal(candidate attr.Type) bool {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.Equal(candidate)
}

func (x *Users) ApplyTerraform5AttributePathStep(step tftypes.AttributePathStep) (interface{}, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ApplyTerraform5AttributePathStep(step)
}

func (x *Users) ValueType(ctx context.Context) attr.Value {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueType(ctx)
}

func (x *Users) ValueFromObject(ctx context.Context, obj basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromObject(ctx, obj)
}

func (x *Group) ResourceSchema() map[string]rschema.Attribute {
	attributes := map[string]rschema.Attribute{
		"name": rschema.StringAttribute{
			Computed:            false,
			Optional:            false,
			Required:            true,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
		"email": rschema.StringAttribute{
			Computed:            false,
			Optional:            true,
			Required:            false,
			Sensitive:           false,
			Description:         "group email address",
			MarkdownDescription: "group email address",
			DeprecationMessage:  "",
		},
		"users": rschema.ListAttribute{
			ElementType:         types.StringType,
			Computed:            false,
			Optional:            true,
			Required:            false,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
	}
	return attributes
}

func (x Group) AttributeDefaultValues(ctx context.Context) map[string]tftypes.Value {
	attributes := map[string]tftypes.Value{
		"users": tftypes.NewValue(tftypes.String, ""),
	}
	return attributes
}

func (x *Group) AttributeTypes() map[string]attr.Type {
	attributes := map[string]attr.Type{
		"name":  types.StringType,
		"email": types.StringType,
		"users": types.ListType{
			ElemType: types.StringType,
		},
	}
	return attributes
}

func (x *Group) WithAttributeTypes(typs map[string]attr.Type) attr.TypeWithAttributeTypes {
	return basetypes.ObjectType{AttrTypes: typs}.WithAttributeTypes(typs)
}

func (x *Group) TerraformType(ctx context.Context) tftypes.Type {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.TerraformType(ctx)
}

func (x *Group) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromTerraform(ctx, in)
}

func (x *Group) Equal(candidate attr.Type) bool {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.Equal(candidate)
}

func (x *Group) ApplyTerraform5AttributePathStep(step tftypes.AttributePathStep) (interface{}, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ApplyTerraform5AttributePathStep(step)
}

func (x *Group) ValueType(ctx context.Context) attr.Value {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueType(ctx)
}

func (x *Group) ValueFromObject(ctx context.Context, obj basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromObject(ctx, obj)
}

func (x *Groups) DatasourceSchema() map[string]dschema.Attribute {
	attributes := map[string]dschema.Attribute{
		"groups": dschema.ListAttribute{
			ElementType:         types.ObjectType{AttrTypes: (&Group{}).AttributeTypes()},
			Computed:            true,
			Optional:            false,
			Required:            false,
			Sensitive:           false,
			Description:         "",
			MarkdownDescription: "",
			DeprecationMessage:  "",
		},
	}
	return attributes
}

func (x Groups) AttributeDefaultValues(ctx context.Context) map[string]tftypes.Value {
	attributes := map[string]tftypes.Value{}
	return attributes
}

func (x *Groups) AttributeTypes() map[string]attr.Type {
	attributes := map[string]attr.Type{
		"groups": types.ListType{
			ElemType: types.ObjectType{AttrTypes: (&Group{}).AttributeTypes()},
		},
	}
	return attributes
}

func (x *Groups) WithAttributeTypes(typs map[string]attr.Type) attr.TypeWithAttributeTypes {
	return basetypes.ObjectType{AttrTypes: typs}.WithAttributeTypes(typs)
}

func (x *Groups) TerraformType(ctx context.Context) tftypes.Type {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.TerraformType(ctx)
}

func (x *Groups) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromTerraform(ctx, in)
}

func (x *Groups) Equal(candidate attr.Type) bool {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.Equal(candidate)
}

func (x *Groups) ApplyTerraform5AttributePathStep(step tftypes.AttributePathStep) (interface{}, error) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ApplyTerraform5AttributePathStep(step)
}

func (x *Groups) ValueType(ctx context.Context) attr.Value {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueType(ctx)
}

func (x *Groups) ValueFromObject(ctx context.Context, obj basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	return basetypes.ObjectType{AttrTypes: x.AttributeTypes()}.ValueFromObject(ctx, obj)
}
